name: Integration UnitTest

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  macos-browser-test:
    strategy:
      matrix:
        node-version: ["14.x", "15.x", "16.x", "17.x", "18.x"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: browser-actions/setup-chromium@latest
      - uses: browser-actions/setup-firefox@latest
      - run: git submodule update --remote --recursive
      - run: npm install
      - run: npm run test
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage1.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

  windows-browser-test:
    strategy:
      matrix:
        node-version: ["14.x", "15.x", "16.x", "17.x", "18.x"]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: browser-actions/setup-chromium@latest
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "84.0"
      - run: git submodule update --remote --recursive
      - run: npm install
      - run: npm run test
