name: Integration UnitTest

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  macos-browser-test:
    strategy:
      matrix:
        node-version: ["14.x"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: browser-actions/setup-chromium@latest
      - uses: browser-actions/setup-firefox@latest
      - run: git submodule update --remote --recursive
      - run: npm install
      - run: npm run test -- --no-watch --no-progress

  windows-browser-test:
    strategy:
      matrix:
        node-version: ["14.x"]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: browser-actions/setup-chromium@latest
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "84.0"
      - run: git submodule update --remote --recursive
      - run: npm install
      - run: npm run test -- --no-watch --no-progress
